import { roundCurrency } from './calculations.js';

export function getYear(dateValue) { return dateValue ? String(dateValue).slice(0, 4) : ''; }
export function getMonth(dateValue) { return dateValue ? String(dateValue).slice(5, 7) : ''; }
export function getQuarter(dateValue) { const month = Number(getMonth(dateValue)); if (!month) return ''; if (month <= 3) return '1'; if (month <= 6) return '2'; if (month <= 9) return '3'; return '4'; }
export function uniqueValues(values) { return Array.from(new Set(values.filter(Boolean))).sort((a, b) => String(a).localeCompare(String(b), 'nl-NL')); }
export function csvEscape(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n;]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
export function toCsv(rows) { return rows.map((row) => row.map(csvEscape).join(';')).join('\n'); }
function makeRows(headers, rows) { return [headers, ...rows]; }
export function downloadFile(fileName, content, mimeType) { const blob = new Blob([content], { type: mimeType }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = fileName; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
export function formatPeriodSuffix(periodType, year, quarter, month) { if (periodType === 'year') return year || 'jaar'; if (periodType === 'quarter') return `${year || 'jaar'}-q${quarter || 'x'}`; if (periodType === 'month') return `${year || 'jaar'}-${month || 'maand'}`; return 'alles'; }
export function filterTripsByExportOptions(trips, options) { return trips.filter((trip) => { const year = getYear(trip.date); const quarter = getQuarter(trip.date); const month = getMonth(trip.date); const userName = trip.sourceUserName || trip.userName; return (options.periodType === 'all' || !options.year || year === options.year) && (options.periodType !== 'quarter' || !options.quarter || quarter === options.quarter) && (options.periodType !== 'month' || !options.month || month === options.month) && (!options.user || userName === options.user) && (!options.customer || trip.customer === options.customer) && (!options.project || trip.project === options.project); }); }
export function summarizeRows(trips, getKey) { const map = new Map(); trips.forEach((trip) => { const key = getKey(trip) || 'Onbekend'; const current = map.get(key) ?? { label: key, businessCompleteTrips: 0, businessKm: 0, totalAmount: 0, incompleteTrips: 0, mileageRates: new Set() }; if (trip.countsForDeduction) { current.businessCompleteTrips += 1; current.businessKm += trip.finalKm; current.totalAmount += trip.deductibleAmount; current.mileageRates.add(trip.mileageRate); } if (trip.validationStatus === 'incompleet') current.incompleteTrips += 1; map.set(key, current); }); return Array.from(map.values()).map((row) => ({ ...row, businessKm: roundCurrency(row.businessKm), totalAmount: roundCurrency(row.totalAmount), mileageRateLabel: Array.from(row.mileageRates).join(' / ') || '' })); }
export function getDuplicateTripCountForTrips(trips, duplicateResult) { const keys = new Set(trips.map((trip) => `${trip.sourceFileName}::${trip.id}::${trip.date}`)); const duplicateKeys = new Set(); duplicateResult.duplicateGroups.forEach((group) => group.trips.forEach((trip) => { const key = `${trip.sourceFileName}::${trip.id}::${trip.date}`; if (keys.has(key)) duplicateKeys.add(key); })); return duplicateKeys.size; }
export function buildAllTripsCsv(trips) { return toCsv(makeRows(['Gebruiker', 'Voertuig', 'Kenteken', 'Bronbestand', 'Periode uit bronbestand', 'Datum', 'Starttijd', 'Eindtijd', 'Startadres', 'Eindadres', 'Klant', 'Project', 'Doel', 'Type rit', 'Kilometers', 'Tarief', 'Bedrag', 'Status', 'Notitie'], trips.map((trip) => [trip.sourceUserName || trip.userName, trip.sourceVehicle, trip.sourceLicensePlate, trip.sourceFileName, `${trip.sourcePeriodFrom || ''} t/m ${trip.sourcePeriodTo || ''}`, trip.date, trip.startTime, trip.endTime, trip.startAddress, trip.endAddress, trip.customer, trip.project, trip.purpose, trip.tripType, trip.finalKm, trip.mileageRate, trip.deductibleAmount, trip.validationStatus, trip.note]))); }
export function buildBookkeeperCsv(trips, periodLabel, duplicateResult) { const rows = summarizeRows(trips, (trip) => trip.sourceUserName || trip.userName); return toCsv(makeRows(['Gebruiker', 'Periode', 'Aantal zakelijke complete ritten', 'Totaal zakelijke kilometers', 'Kilometertarief', 'Totaal bedrag', 'Aantal incomplete ritten', 'Aantal mogelijke dubbele ritten'], rows.map((row) => { const userTrips = trips.filter((trip) => (trip.sourceUserName || trip.userName) === row.label); return [row.label, periodLabel, row.businessCompleteTrips, row.businessKm, row.mileageRateLabel, row.totalAmount, row.incompleteTrips, getDuplicateTripCountForTrips(userTrips, duplicateResult)]; }))); }
export function buildSummaryCsv(trips, firstHeader, getKey) { const rows = summarizeRows(trips, getKey); return toCsv(makeRows([firstHeader, 'Aantal zakelijke complete ritten', 'Zakelijke kilometers', 'Totaal bedrag', 'Aantal incomplete ritten'], rows.map((row) => [row.label, row.businessCompleteTrips, row.businessKm, row.totalAmount, row.incompleteTrips]))); }
export function getExportSummary(trips, duplicateResult) { const completeBusinessTrips = trips.filter((trip) => trip.countsForDeduction); const incompleteTrips = trips.filter((trip) => trip.validationStatus === 'incompleet'); return { totalTrips: trips.length, completeBusinessTrips: completeBusinessTrips.length, businessKm: roundCurrency(completeBusinessTrips.reduce((total, trip) => total + trip.finalKm, 0)), totalAmount: roundCurrency(completeBusinessTrips.reduce((total, trip) => total + trip.deductibleAmount, 0)), incompleteTrips: incompleteTrips.length, duplicateTrips: getDuplicateTripCountForTrips(trips, duplicateResult) }; }
export function buildCombinedJsonBackup({ filteredTrips, importedFiles, options, summary, exportedAt = new Date().toISOString() }) { return { appName: 'KM Dashboard', exportFormatVersion: '1.0', exportedAt, period: { type: options.periodType, year: options.year, quarter: options.quarter, month: options.month }, filters: { user: options.user, customer: options.customer, project: options.project }, summary, importedFiles: importedFiles.map((file) => ({ fileName: file.fileName, status: file.status, errors: file.errors, warnings: file.warnings })), trips: filteredTrips }; }
